---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls-cert
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/part-of: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - homelab.mcagr.com
