apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-tls-cert
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
spec:
  secretName: gitea-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - git.mcagr.com