apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-admin-credentials
  namespace: gitea
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: onepassword 
    kind: ClusterSecretStore
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
  data:
    # --- Item 1: The Credentials ---
    - secretKey: username
      remoteRef:
        key: "gitea-admin/username"
    - secretKey: password
      remoteRef:
        key: "gitea-admin/password"
        
    # --- Item 2: The Email Address ---
    - secretKey: email
      remoteRef:
        key: "gitea-email/username" # 