apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8bot-tokens-eso
  namespace: k8bot
spec:
  refreshInterval: "12h"
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: k8bot-slack-secrets
    creationPolicy: Owner
  data:
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: "kubebot_app_token/credential"
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: "kubebot_oauth_token/credential"