apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: botkube-communications
  namespace: botkube
  labels:
    botkube.io/config-watch: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: botkube-communications
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        comm_config.yaml: |
          communications:
            default-group:
              socketSlack:
                enabled: true
                channels:
                  default:
                    name: "kubebot"
                    bindings:
                      executors:
                        - kubectl-read-only
                        - argocd
                      sources:
                        - kubernetes-errors
                        - argocd-events
                botToken: "{{ .SLACK_BOT_TOKEN }}"
                appToken: "{{ .SLACK_APP_TOKEN }}"
  data:
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: "kubebot_app_token/credential"
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: "kubebot_user_oauth_token/credential"