apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: botkube-slack-credentials
  namespace: botkube
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: botkube-slack-secret
    creationPolicy: Owner
  data:
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: kubebot_app_token/password 
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: kubebot_user_oauth_token/password